-- Post-payment trust: a stored invoice, saved addresses, and gift orders.
--
-- 1. orders.invoice
--    An invoice must not change when the catalogue does. Until now the receipt
--    was assembled in the browser from whatever the page happened to hold, so
--    it existed only for as long as that tab did and could not be shown to the
--    customer later or checked by the studio at all. The invoice is now frozen
--    at purchase time as a JSON snapshot: line items, unit prices, discounts,
--    shipping and totals exactly as charged. Editing an artwork's price later
--    cannot alter a past receipt.
--
-- 2. Gift orders
--    A piece bought as a present goes to someone who did not pay for it, so
--    the delivery name differs from the buyer and no price may appear in the
--    parcel.
--
-- 3. user_addresses
--    One address per account forces re-typing for every destination. Buyers
--    send work to homes, offices and other people.

alter table if exists public.orders
  add column if not exists invoice jsonb,
  add column if not exists is_gift boolean not null default false,
  add column if not exists gift_message text,
  add column if not exists gift_recipient_name text;

comment on column public.orders.invoice is
  'Frozen billing snapshot as charged. Never recomputed from current prices.';

create table if not exists public.user_addresses (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_accounts(id) on delete cascade,
  label text,
  recipient_name text not null,
  phone text not null,
  house text not null,
  street text not null,
  landmark text,
  city text not null,
  state text not null,
  pincode text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.user_addresses
  drop constraint if exists user_addresses_pincode_format;

alter table if exists public.user_addresses
  add constraint user_addresses_pincode_format
  check (pincode ~ '^[1-9][0-9]{5}$');

create index if not exists user_addresses_user_id_idx
  on public.user_addresses (user_id, is_default desc, updated_at desc);

-- At most one default per account. A partial unique index expresses that
-- directly, so the rule cannot be broken by a concurrent write.
create unique index if not exists user_addresses_one_default_per_user
  on public.user_addresses (user_id)
  where is_default;

-- Same lockdown as every other table: no direct client access.
alter table public.user_addresses enable row level security;

drop policy if exists user_addresses_deny_client_access on public.user_addresses;
create policy user_addresses_deny_client_access
  on public.user_addresses
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);
