-- Carrier tracking, stock reservations, and server-side carts.
--
-- 1. Shipment details
--    "Shipped" with nothing to track is where the "where is it?" emails start.
--    The courier and consignment number are recorded on the order and included
--    in the dispatch email.
--
-- 2. Stock reservations
--    Stock is currently claimed only after payment is verified, so two buyers
--    can both reach Razorpay for the same one-of-one piece and both be charged.
--    The loser is detected and refunded by hand. A short reservation taken when
--    the payment order is created closes that window: the piece is held for the
--    duration of checkout and released automatically if payment never arrives.
--
--    Reservations are advisory — the compare-and-swap on quantity remains the
--    authority at order time. This narrows the race rather than replacing the
--    mechanism that makes it safe.
--
-- 3. Server-side carts
--    A cart in localStorage does not survive moving from a phone to a laptop.

alter table if exists public.orders
  add column if not exists courier_name text,
  add column if not exists tracking_number text,
  add column if not exists tracking_url text;

comment on column public.orders.tracking_number is
  'Carrier consignment/AWB number, shown to the buyer once dispatched.';

create table if not exists public.artwork_reservations (
  id bigint generated by default as identity primary key,
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  reservation_token text not null,
  razorpay_order_id text,
  customer_email text,
  expires_at timestamptz not null,
  released_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists artwork_reservations_artwork_idx
  on public.artwork_reservations (artwork_id, expires_at desc);

create index if not exists artwork_reservations_token_idx
  on public.artwork_reservations (reservation_token);

-- One live reservation per artwork. A partial unique index expresses the rule
-- in the database, so two concurrent checkouts cannot both hold the same piece
-- however the application behaves.
create unique index if not exists artwork_reservations_one_active_per_artwork
  on public.artwork_reservations (artwork_id)
  where released_at is null;

create table if not exists public.user_carts (
  user_id bigint primary key references public.user_accounts(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

-- Expired reservations are released rather than deleted, so a support question
-- about a stuck checkout can still be answered.
create or replace function public.release_expired_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  released integer := 0;
begin
  update public.artwork_reservations
  set released_at = timezone('utc', now())
  where released_at is null
    and expires_at < timezone('utc', now());

  get diagnostics released = row_count;
  return released;
end;
$$;

do $$
declare
  target text;
begin
  foreach target in array array['artwork_reservations', 'user_carts']
  loop
    execute format('alter table public.%I enable row level security', target);
    execute format('drop policy if exists %I on public.%I', target || '_deny_client_access', target);
    execute format(
      'create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',
      target || '_deny_client_access',
      target
    );
  end loop;
end
$$;
